title: My First Pages
author: Dimas Clever
email: dium@yandex.ru
description: > # this means to ignore newlines until "baseurl:"
  My First WEB Pages

# social links
twitter_username: @Dium75
github_username:  Dimas Clever

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
