title: Dimas Clever
author: Dimas Clever
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Это мой первый опыт

# social links
twitter_username: @Dium75
github_username:  Dimas Clever

show_excerpts: true # set to false to remove excerpts on the homepage

theme:hacker
